Mark _ as unreachable
Rust's exhaustiveness checking is based entirely on enums and never
values, so this fails because u8 simply isn't an enum type.

    error[E0004]: non-exhaustive patterns: `_` not covered
      --> src/main.rs:39:26
       |
    39 |     let op_bytes = match op_code {
       |                          ^^^^^^^ pattern `_` not covered

https://github.com/rust-lang/rust/issues/12483